### ISSUE TITLE
Internal links to anchor tags broken

### ISSUE THREAD

**Issue by caseywatts** [ember-fastboot/fastboot-website#45]
Anchor links aren't working in `https://www.ember-fastboot.com/docs/user-guide` for example, the link "Tips & Tricks".
[This url](https://www.ember-fastboot.com/docs/user-guide#tips-and-tricks) a user might suspect would take them to the right part of the page.

The link is being generated exactly how I would suspect it to be: ([markdown source code line](https://github.com/ember-fastboot/fastboot-website/blame/master/markdown/docs/user-guide.md#L15)) Also, the `href` attribute looks correct in the DOM on my computer after rendering). But it ends up sending the user to a link that looks like `https://www.ember-fastboot.com/#tips-and-tricks`

I suspect ember just doesn't work well with traditional anchor tags in general. ([related](https://github.com/mike-north/ember-anchor)).

We may want to remove anchor tags from the markdown docs, or look into making this work.

(Somewhat related, and I'm not sure it applies here, anchor tags behave differently in different browsers etc, to see a longer discussion about this see [here](https://github.com/adam-p/markdown-here/issues/93))

---

❤️ ❤️

**Comment by davidpett** [comment]
@caseywatts this is due to remarkable not adding `id` attributes to the heading elements. This feature is requested and as soon as it is added, we will update. Thanks

**Comment by caseywatts** [comment]
Do we have word that this feature is being considered/added?

I see this issue that's been closed:
https://github.com/jonschlinkert/remarkable/issues/122

**Comment by caseywatts** [comment]
When I try to add the id manually, it still isn't fixed:
- I manually add an `id` to the header tag in the chrome inspector
- I try to click the link "Tips and Tricks"
- I am navigated to `https://www.ember-fastboot.com/#tips-and-tricks` which is the same page as `https://www.ember-fastboot.com/` - no longer on the User Guide page.

It seems there are at least two issues present:
- remarkable doesn't add `id` (or `name`)
- the links are being generated incorrectly

**Comment by jurecuhalev** [comment]
You can write headers like this to get ids:

`### Use Model Hooks to Defer Rendering<a name="#defer-rendering-with-model-hooks"></a>`

**Comment by jurecuhalev** [comment]
Ok, I got this working. Steps:

Write headings as:

```
<a name="defer-rendering-with-model-hooks"></a>
### Use Model Hooks to Defer Rendering
```

This inserts anchors before the header, so when you scroll down to it, you still see header. Alternative is as:

```
### Use Model Hooks to Defer Rendering <a name="defer-rendering-with-model-hooks"></a>
```

But then header gets hidden.

When linking, use this:
```
See [Defer Rendering with Model Hooks](/docs/user-guide#defer-rendering-with-model-hooks).
```
`/docs/user-guide` is important part

If this looks as a good workaround, I'm happy to go through the docs and update markdown files.

**Comment by davidpett** [comment]
fixed with https://github.com/ember-fastboot/fastboot-website/pull/65
